### PR TITLE
Pf  firebase functions

### PR DESCRIPTION
**Pull request by firefox0102**
Firebase function for exporting from collection sites page!!!

### CODE REVIEW

**Comment by firefox0102** [comment]
@lslangley should we also implement this on the site reports page and just dump that js plugin? Yes, I answered my own question

**Review by lslangley — COMMENTED** [review]
thumbs up.

**Comment by lslangley** [comment]
thumbs up.

**Review by lslangley — APPROVED** [review]
thumbs up and approved.

**Pull request merged**
